from __future__ import annotations

VERSION = "0.9.0"

EVENT_TYPES = (
    "EARNINGS_RESULT",
    "GUIDANCE_CHANGE",
    "CAPITAL_ALLOCATION",
    "SHARE_REPURCHASE",
    "DIVIDEND_CHANGE",
    "DEBT_ISSUANCE",
    "DEBT_REPAYMENT",
    "ACQUISITION",
    "DIVESTITURE",
    "PARTNERSHIP",
    "CUSTOMER_WIN",
    "CUSTOMER_LOSS",
    "SUPPLY_CHANGE",
    "CAPACITY_EXPANSION",
    "CAPEX_CHANGE",
    "MANAGEMENT_CHANGE",
    "CEO_CHANGE",
    "CFO_CHANGE",
    "RESTRUCTURING",
    "LAYOFF",
    "REGULATORY",
    "LITIGATION",
    "PRODUCT_LAUNCH",
    "PRODUCT_DELAY",
    "SECURITY_INCIDENT",
    "ACCOUNTING_CHANGE",
    "RESTATEMENT",
    "SEGMENT_CHANGE",
    "OTHER_MATERIAL_EVENT",
)

DIRECTIONS = (
    "POSITIVE",
    "NEGATIVE",
    "MIXED",
    "NEUTRAL",
    "INSUFFICIENT_EVIDENCE",
)

MATERIALITY = ("LOW", "MEDIUM", "HIGH", "CRITICAL")
EVENT_STATUSES = ("REALIZED", "ANNOUNCED", "PENDING", "COMPLETED", "CANCELLED", "UNKNOWN")
CATALYST_STATUSES = ("UPCOMING", "IN_PROGRESS", "REALIZED", "MISSED", "CANCELLED", "UNKNOWN")
CATALYST_CLASSES = (
    "POSITIVE_CATALYST",
    "NEGATIVE_CATALYST",
    "RISK_EVENT",
    "STRUCTURAL_CHANGE",
    "INFORMATIONAL",
)

THESIS_DIMENSIONS = (
    "business_quality",
    "financial_quality",
    "growth_outlook",
    "valuation_attractiveness",
    "risk_level",
)

WARNINGS = (
    "NO_MATERIAL_EVENTS",
    "EVENT_SOURCE_INCOMPLETE",
    "EVENT_DATE_UNCERTAIN",
    "EVENT_DUPLICATE_COLLAPSED",
    "EVENT_MATERIALITY_UNCERTAIN",
    "UPCOMING_CATALYST_DATE_UNCONFIRMED",
    "EVENT_SNAPSHOT_RELATION_UNKNOWN",
)
